// Most-missed physics questions. answer = index into choices.
window.QUIZ = {
  kinematics: { title: "Kinematics", questions: [
    { q: "A ball is thrown straight up. At the very top of its path, which is true?", choices: ["v = 0 and a = 0", "v = 0 and a = 9.8 m/s² downward", "v = 9.8 m/s and a = 0", "v is upward and a is upward"], answer: 1, why: "Gravity still acts, so acceleration is 9.8 m/s² downward even while velocity is momentarily zero. Misconception: zero velocity means zero acceleration." },
    { q: "A car has velocity −10 m/s and acceleration −2 m/s². The car is:", choices: ["Slowing down", "Speeding up", "At rest", "Moving at constant speed"], answer: 1, why: "Velocity and acceleration have the same sign, so speed increases. Negative acceleration does not always mean slowing down." },
    { q: "A runner goes 100 m east then 100 m west in 40 s. Average velocity is:", choices: ["5 m/s", "0 m/s", "2.5 m/s", "−5 m/s"], answer: 1, why: "Displacement is zero, so average velocity is zero. Average speed would be 200 m / 40 s = 5 m/s." },
    { q: "On a velocity–time graph, the area under the line represents:", choices: ["Acceleration", "Displacement", "Force", "Average speed"], answer: 1, why: "Slope = acceleration; area = displacement (v × t)." },
    { q: "You drive 60 km at 30 km/h, then 60 km at 60 km/h. Average speed for the trip?", choices: ["45 km/h", "40 km/h", "50 km/h", "30 km/h"], answer: 1, why: "Total distance 120 km, time 2 h + 1 h = 3 h → 40 km/h. Averaging the two speeds ignores time spent at each." },
    { q: "In air-free conditions, a bowling ball and a tennis ball are dropped together. The bowling ball:", choices: ["Lands first", "Lands second", "Lands at the same time", "Cannot be determined"], answer: 2, why: "Both accelerate at g. Mass cancels in free fall (a = F/m = mg/m)." },
    { q: "A car starts from rest and accelerates at 4 m/s² for 5 s. How far does it travel?", choices: ["20 m", "50 m", "100 m", "10 m"], answer: 1, why: "Δx = ½at² = ½(4)(25) = 50 m. 20 m is v (4×5) — not distance." },
    { q: "Which x–t graph shape means constant positive acceleration?", choices: ["Straight line sloping up", "Horizontal line", "Upward-curving parabola", "Straight line sloping down"], answer: 2, why: "A straight line means constant velocity. A curve means the slope (velocity) is changing, so there is acceleration." }
  ]},
  projectile: { title: "Projectile Motion", questions: [
    { q: "One ball is dropped and another is launched horizontally from the same height at the same instant. Ignoring air resistance:", choices: ["Dropped ball lands first", "Launched ball lands first", "They land together", "Depends on the launch speed"], answer: 2, why: "Vertical motion is independent of horizontal motion, so both fall for the same time." },
    { q: "At the highest point of a projectile's path (angled launch), its velocity is:", choices: ["Zero", "Entirely horizontal", "Entirely vertical", "Equal to the launch speed"], answer: 1, why: "v_y = 0 at the top but vₓ is unchanged, so the speed equals vₓ = v cosθ." },
    { q: "The acceleration of a projectile at the top of its path is:", choices: ["Zero", "g, downward", "g, horizontal", "Depends on the launch speed"], answer: 1, why: "Gravity acts the whole time. Only the vertical component of velocity is zero at the top." },
    { q: "To find how long a horizontally launched object stays in the air, you use:", choices: ["The horizontal speed and range", "The vertical drop height and g", "The launch speed only", "The mass of the object"], answer: 1, why: "t = √(2h/g). Only the vertical motion determines the time." },
    { q: "Without air resistance, which launch angle gives the greatest range on level ground?", choices: ["30°", "45°", "60°", "90°"], answer: 1, why: "R = v² sin(2θ)/g is maximum when sin(2θ) = 1, i.e., θ = 45°." },
    { q: "A ball kicked at 20 m/s and 30° above horizontal has a horizontal velocity of about:", choices: ["10 m/s", "17.3 m/s", "20 m/s", "11.5 m/s"], answer: 1, why: "vₓ = 20 cos30° = 17.3 m/s. 10 m/s is the vertical component (20 sin30°)." },
    { q: "Two projectiles have the same speed; one is launched at 30°, the other at 60°. Compared with the 30° shot, the 60° shot has:", choices: ["Shorter range, lower height", "The same range, greater height", "Greater range, same height", "The same range and height"], answer: 1, why: "Complementary angles give equal ranges, but the steeper launch goes higher and stays up longer." },
    { q: "A heavier cannonball and a lighter one are fired with the same speed and angle (no air). The heavier one:", choices: ["Goes farther", "Goes less far", "Lands at the same place", "Stays up longer"], answer: 2, why: "Mass does not appear in the projectile equations when only gravity acts." }
  ]},
  newton: { title: "Newton's Laws", questions: [
    { q: "A hockey puck slides at constant velocity on frictionless ice. The net force on it is:", choices: ["Forward and nonzero", "Zero", "Equal to its weight", "Equal to its momentum"], answer: 1, why: "Newton's first law: constant velocity means zero net force. No force is needed to keep it moving." },
    { q: "A truck hits a bug. During the collision, the force of the truck on the bug is ___ the force of the bug on the truck.", choices: ["Larger than", "Smaller than", "Equal to", "Zero compared to"], answer: 2, why: "Third law: equal magnitude, opposite direction. The bug's acceleration is huge because its mass is tiny." },
    { q: "Why don't action–reaction forces cancel each other?", choices: ["They are not equal in size", "They act on different objects", "They occur at different times", "One is always larger"], answer: 1, why: "Net force is the sum of forces on one object. Third-law pairs act on two different objects." },
    { q: "A 5 kg block rests on a 30° frictionless incline. Compared with mg, the normal force is:", choices: ["Equal to mg", "Greater than mg", "mg cos30°, less than mg", "Zero"], answer: 2, why: "N balances the component of weight perpendicular to the surface: mg cosθ. N ≠ mg except on level ground with no other vertical forces." },
    { q: "A skydiver falls at terminal velocity. The net force on her is:", choices: ["Her weight, downward", "Zero", "Air resistance, upward", "Greater than her weight"], answer: 1, why: "Constant velocity → ΣF = 0, so drag equals weight." },
    { q: "A 10 kg box is pushed with 40 N while friction is 10 N. Acceleration?", choices: ["4 m/s²", "3 m/s²", "5 m/s²", "1 m/s²"], answer: 1, why: "a = ΣF/m = (40 − 10)/10 = 3 m/s². Use net force." },
    { q: "In an elevator accelerating upward, a scale under you reads:", choices: ["Less than your weight", "Your weight", "More than your weight", "Zero"], answer: 2, why: "N − mg = ma → N = m(g + a), larger than mg. Your mass stays the same." },
    { q: "Doubling the contact area of a sliding block (same weight, same surface) does what to kinetic friction?", choices: ["Doubles it", "Halves it", "Roughly no change", "Makes it zero"], answer: 2, why: "f = μN does not depend on area (to a good approximation); pressure goes down while area goes up." }
  ]},
  momentum: { title: "Momentum", questions: [
    { q: "In an inelastic collision between two carts on a frictionless track:", choices: ["Momentum is lost", "Kinetic energy is conserved", "Momentum is conserved and kinetic energy decreases", "Neither is conserved"], answer: 2, why: "With no external net force, momentum is conserved in all collisions. KE becomes thermal, sound, deformation." },
    { q: "Why does an airbag reduce injury in a crash?", choices: ["It reduces the change in momentum", "It increases the time of the collision, lowering the average force", "It increases the impulse", "It reduces the mass of the passenger"], answer: 1, why: "Δp is the same; F = Δp/Δt, so a longer Δt means a smaller force." },
    { q: "A 2 kg cart at 3 m/s sticks to a stationary 1 kg cart. Final speed?", choices: ["3 m/s", "2 m/s", "1 m/s", "1.5 m/s"], answer: 1, why: "(2)(3) = (3)v → v = 2 m/s." },
    { q: "A ball hits a wall and bounces back at the same speed. Compared with a ball that sticks to the wall, the bounce delivers:", choices: ["Less impulse", "The same impulse", "About twice the impulse", "Zero impulse"], answer: 2, why: "Bounce: Δp = m(v − (−v)) = 2mv. Sticking: Δp = mv. Direction reversal matters." },
    { q: "Momentum is a:", choices: ["Scalar", "Vector", "Force", "Type of energy"], answer: 1, why: "It points in the direction of velocity, so opposite directions need opposite signs." },
    { q: "A big truck and a small car collide head-on. Which experiences the greater impulse magnitude?", choices: ["Truck", "Car", "Both the same", "Cannot tell"], answer: 2, why: "The forces are equal and last equally long (third law), so impulses are equal and opposite. The car's velocity changes more because its mass is smaller." },
    { q: "A 60 kg skater and a 40 kg skater push apart from rest. The 40 kg skater moves at 3 m/s. The other moves at:", choices: ["3 m/s", "2 m/s", "4.5 m/s", "1 m/s"], answer: 1, why: "Total p = 0: 60v = 40(3) → v = 2 m/s in the opposite direction." },
    { q: "The area under a force–time graph represents:", choices: ["Work", "Impulse", "Power", "Acceleration"], answer: 1, why: "J = ∫F dt = Δp." }
  ]},
  energy: { title: "Work & Energy", questions: [
    { q: "A car doubles its speed. Its kinetic energy:", choices: ["Doubles", "Triples", "Quadruples", "Stays the same"], answer: 2, why: "KE = ½mv². Doubling v multiplies KE by 4, so stopping distance also quadruples." },
    { q: "A student holds a heavy box stationary for 1 minute. The work done on the box is:", choices: ["Large", "Equal to mg × 60", "Zero", "Negative"], answer: 2, why: "No displacement → no work on the box (the student still gets tired, but that's internal energy use)." },
    { q: "Two frictionless hills; a 1 kg and a 10 kg block slide from the same height. Speeds at the bottom compare as:", choices: ["The 10 kg is faster", "The 1 kg is faster", "Equal", "Depends on the slope angle"], answer: 2, why: "mgh = ½mv² → v = √(2gh). Mass cancels; slope shape doesn't matter without friction." },
    { q: "Moving a box up a ramp instead of lifting it straight up (frictionless ramp) changes:", choices: ["The work done against gravity", "The force required", "The final potential energy", "Nothing"], answer: 1, why: "The ramp reduces the force but increases the distance. The work and ΔPE are the same." },
    { q: "Two motors lift the same load the same height. Motor A takes 10 s; B takes 20 s. Which statement is correct?", choices: ["A does more work", "A has more power", "B has more power", "They have the same power"], answer: 1, why: "Same work; P = W/t, so the quicker one has twice the power." },
    { q: "A force of 10 N is applied perpendicular to a block's displacement of 3 m. Work done by that force?", choices: ["30 J", "10 J", "0 J", "3 J"], answer: 2, why: "W = Fd cosθ, with θ = 90°, so W = 0 (e.g., normal force, centripetal force)." },
    { q: "A skier slides down a slope and ends with less KE than the initial PE. Where did the energy go?", choices: ["It was destroyed", "It became thermal energy through friction", "It became more potential energy", "It was never there"], answer: 1, why: "Energy is conserved overall; friction converts mechanical energy into thermal energy in the skis and snow." },
    { q: "A spring (k = 200 N/m) is compressed 0.1 m. The stored elastic energy is:", choices: ["20 J", "1 J", "10 J", "0.1 J"], answer: 1, why: "PE = ½kx² = ½(200)(0.01) = 1 J. Don't forget to square x." }
  ]}
};
