// Most-missed questions per topic. Use g = 10 m/s^2 unless stated.
// answer = index into choices. why = explanation shown after answering.
// trap = the misconception this question is designed to expose.
window.QUIZ_DATA = [
  {
    id: "kinematics", title: "Kinematics", color: "#2563eb",
    questions: [
      { q: "A car travels east and the driver brakes, slowing down. What is the direction of the car's acceleration?",
        choices: ["East", "West", "Zero, because the car is still moving", "Upward"],
        answer: 1, trap: "Acceleration always points the way velocity is changing, not the way the object moves.",
        why: "Velocity points east and is getting smaller, so Δv points west. Slowing down = acceleration opposite to velocity." },
      { q: "A ball is thrown straight up. At the very top of its path, what are its velocity and acceleration?",
        choices: ["v = 0, a = 0", "v = 0, a = 10 m/s² downward", "v = 10 m/s up, a = 0", "v = 0, a = 10 m/s² upward"],
        answer: 1, trap: "Zero velocity does not mean zero acceleration.",
        why: "Gravity acts the whole flight. At the top the velocity is momentarily zero but is still changing by 10 m/s every second, downward." },
      { q: "You walk 30 m east, then 40 m west. What are your distance and displacement?",
        choices: ["Distance 70 m, displacement 10 m west", "Distance 10 m, displacement 70 m", "Distance 70 m, displacement 70 m west", "Distance 10 m west, displacement 10 m west"],
        answer: 0, trap: "Distance is a total path length (scalar); displacement is a straight-line change in position (vector).",
        why: "Path length = 30 + 40 = 70 m. Net change in position = 30 − 40 = −10 m, i.e. 10 m west." },
      { q: "On a velocity–time graph, what does the SLOPE of the line represent?",
        choices: ["Displacement", "Velocity", "Acceleration", "Distance"],
        answer: 2, trap: "Students mix up slope and area, and mix up position–time vs velocity–time graphs.",
        why: "Slope = Δv/Δt = acceleration. The AREA under a v–t graph is displacement. Slope of a position–time graph is velocity." },
      { q: "A car starts from rest and accelerates at 2 m/s² for 5 s. How far does it travel?",
        choices: ["10 m", "25 m", "50 m", "5 m"],
        answer: 1, trap: "Using d = vt with the final speed (10 m/s × 5 s = 50 m) ignores that speed grew gradually.",
        why: "d = v₀t + ½at² = 0 + ½(2)(5²) = 25 m. Average speed was 5 m/s, not 10." },
      { q: "You drive the first half of a trip's DISTANCE at 60 km/h and the second half at 40 km/h. What is your average speed?",
        choices: ["50 km/h", "48 km/h", "52 km/h", "100 km/h"],
        answer: 1, trap: "Average speed = total distance ÷ total time, not the average of the two speeds.",
        why: "Take 120 km total: 60 km at 60 km/h = 1 h, 60 km at 40 km/h = 1.5 h. 120 km ÷ 2.5 h = 48 km/h." },
      { q: "A heavy bowling ball and a light tennis ball are dropped from the same height in a vacuum. Which lands first?",
        choices: ["The bowling ball", "The tennis ball", "They land together", "It depends on the height only"],
        answer: 2, trap: "Heavier things do not fall faster; air resistance, not mass, causes differences in everyday life.",
        why: "Free-fall acceleration is g for every mass. Weight is larger for the bowling ball, but so is its inertia, and they cancel." }
    ]
  },
  {
    id: "projectile", title: "Projectile Motion", color: "#059669",
    questions: [
      { q: "Ignoring air resistance, what is the horizontal acceleration of a projectile in flight?",
        choices: ["10 m/s² forward", "10 m/s² backward", "Zero", "It depends on launch speed"],
        answer: 2, trap: "Students think something must keep pushing the object forward.",
        why: "No horizontal force acts after launch, so horizontal velocity stays constant. Only gravity acts, vertically." },
      { q: "One ball is dropped from a table. A second ball is rolled horizontally off the same table at the same moment. Which hits the floor first?",
        choices: ["The dropped ball", "The rolled ball", "They land at the same time", "Cannot be determined"],
        answer: 2, trap: "Horizontal and vertical motions are independent.",
        why: "Both start with zero vertical velocity and fall the same height with the same g, so the fall times are equal." },
      { q: "A soccer ball is kicked at an angle. At the highest point of its path, what is true?",
        choices: ["Velocity is zero", "Velocity is horizontal and not zero", "Acceleration is zero", "Speed is at its maximum"],
        answer: 1, trap: "Students treat the apex like the top of a straight-up throw.",
        why: "Only the vertical component is zero at the top. The horizontal component (v cos θ) remains, so speed is at its minimum, not zero." },
      { q: "A ball is rolled horizontally at 20 m/s off a 45 m cliff. How far from the base of the cliff does it land? (g = 10 m/s²)",
        choices: ["20 m", "45 m", "60 m", "90 m"],
        answer: 2, trap: "Skipping the fall-time step, or using the cliff height as the horizontal distance.",
        why: "Fall time: 45 = ½(10)t² → t = 3 s. Horizontal distance = 20 m/s × 3 s = 60 m." },
      { q: "On level ground and ignoring air, which pair of launch angles (same speed) gives the SAME range?",
        choices: ["30° and 45°", "30° and 60°", "20° and 50°", "45° and 90°"],
        answer: 1, trap: "Only 45° gives maximum range, but complementary angles tie.",
        why: "Range ∝ sin 2θ, and sin 60° = sin 120°, so θ and (90° − θ) land at the same spot. The 60° shot just stays in the air longer." },
      { q: "A ball is launched at 20 m/s at 30° above horizontal. What is its initial vertical velocity, and how long to reach the top? (g = 10 m/s²)",
        choices: ["20 m/s, 2 s", "17.3 m/s, 1.7 s", "10 m/s, 1 s", "10 m/s, 2 s"],
        answer: 2, trap: "Using cos instead of sin for the vertical component, or using the full speed.",
        why: "v_y = 20 sin 30° = 10 m/s. Time to top = v_y / g = 10 / 10 = 1 s." },
      { q: "You double the launch speed of a projectile (same angle, level ground, no air). What happens to the range?",
        choices: ["Doubles", "Triples", "Quadruples", "Stays the same"],
        answer: 2, trap: "Assuming linear scaling.",
        why: "Range = v² sin 2θ / g. Range depends on v², so doubling v gives 4× the range." }
    ]
  },
  {
    id: "newton", title: "Newton's Laws", color: "#d97706",
    questions: [
      { q: "A hockey puck slides at constant velocity across frictionless ice. What is the net force on it?",
        choices: ["Forward force equal to its motion", "Zero", "Equal to its weight", "Depends on its speed"],
        answer: 1, trap: "Force is needed to keep an object moving (Aristotle's idea).",
        why: "Newton's first law: constant velocity means net force = 0. Force changes motion; it does not maintain it." },
      { q: "A truck collides head-on with a small car. During the collision, which statement is true?",
        choices: ["The truck exerts a larger force on the car", "The car exerts a larger force on the truck", "The forces are equal in size and opposite in direction", "The forces are equal and in the same direction"],
        answer: 2, trap: "Bigger or faster objects do not push harder in an interaction.",
        why: "Third law: the two forces are always equal and opposite. The car's acceleration is larger only because its mass is smaller (a = F/m)." },
      { q: "A book rests on a table. Which force is the Newton's THIRD-law partner of the book's weight (Earth pulling down on the book)?",
        choices: ["The table's normal force on the book", "The book pulling up on Earth", "The table pushing down on the floor", "Friction"],
        answer: 1, trap: "Normal force and weight are equal here, but they are not an action–reaction pair.",
        why: "A third-law pair acts on different objects and is the same type of force. Earth pulls book (gravity) ↔ book pulls Earth (gravity)." },
      { q: "A 5 kg rock is taken to the Moon, where g = 1.6 m/s². What are its mass and weight there?",
        choices: ["5 kg and 50 N", "0.8 kg and 8 N", "5 kg and 8 N", "5 kg and 0 N"],
        answer: 2, trap: "Mass and weight are different quantities.",
        why: "Mass is the amount of matter and does not change: 5 kg. Weight = mg = 5 × 1.6 = 8 N." },
      { q: "A 10 kg crate is pushed right with 30 N while friction pushes left with 10 N. What is its acceleration?",
        choices: ["3 m/s²", "2 m/s²", "4 m/s²", "1 m/s²"],
        answer: 1, trap: "Using the applied force instead of the NET force.",
        why: "F_net = 30 − 10 = 20 N. a = F_net / m = 20 / 10 = 2 m/s² to the right." },
      { q: "You stand on a scale in an elevator that is accelerating upward. The scale reading is...",
        choices: ["Less than your weight", "Equal to your weight", "Greater than your weight", "Zero"],
        answer: 2, trap: "Weight and apparent weight (normal force) are different.",
        why: "N − mg = ma with a upward, so N = m(g + a) > mg. The scale reads the normal force." },
      { q: "A box slides on a rough floor. If you double the box's weight (same surfaces), what happens to the kinetic friction force?",
        choices: ["It stays the same", "It doubles", "It halves", "It quadruples"],
        answer: 1, trap: "Thinking friction depends on surface area or speed.",
        why: "f = μN. Doubling the weight doubles the normal force on a level floor, so friction doubles. Contact area does not matter." }
    ]
  },
  {
    id: "momentum", title: "Momentum", color: "#7c3aed",
    questions: [
      { q: "Which is the correct unit of momentum?",
        choices: ["kg·m/s²", "kg·m/s", "kg·m²/s²", "N·m"],
        answer: 1, trap: "Mixing up momentum, force and energy units.",
        why: "p = mv has units kg·m/s, which is the same as N·s (impulse). kg·m/s² is newtons; kg·m²/s² is joules." },
      { q: "An airbag increases the time of a collision. Why does that protect you?",
        choices: ["It reduces your change in momentum", "It reduces the average force on you for the same change in momentum", "It increases your momentum", "It removes your kinetic energy"],
        answer: 1, trap: "Thinking the airbag changes the momentum change.",
        why: "Impulse FΔt = Δp. You must still stop (same Δp), but a larger Δt means a smaller average force F." },
      { q: "A 1000 kg car moving at 20 m/s hits a stationary 1000 kg car and they lock together. How fast do they move after?",
        choices: ["20 m/s", "10 m/s", "5 m/s", "0 m/s"],
        answer: 1, trap: "Forgetting the combined mass.",
        why: "Momentum is conserved: (1000)(20) = (2000)v → v = 10 m/s." },
      { q: "In the collision above (cars lock together), what is conserved?",
        choices: ["Momentum only", "Kinetic energy only", "Both momentum and kinetic energy", "Neither"],
        answer: 0, trap: "Assuming energy is conserved whenever momentum is.",
        why: "Momentum is conserved in every isolated collision. KE before = 200,000 J, after = 100,000 J; half was converted to heat, sound and deformation." },
      { q: "Two carts at rest, 2 kg and 4 kg, are pushed apart by a spring. The 2 kg cart moves left at 3 m/s. How fast does the 4 kg cart move?",
        choices: ["3 m/s right", "1.5 m/s right", "6 m/s right", "1.5 m/s left"],
        answer: 1, trap: "Ignoring direction, so momentum 'adds' instead of cancelling.",
        why: "Total momentum stays 0: 2(−3) + 4v = 0 → v = +1.5 m/s (right)." },
      { q: "A ball hits a wall. In Case A it sticks. In Case B it bounces straight back at the same speed. In which case does the wall give the ball a larger impulse?",
        choices: ["Case A (sticks)", "Case B (bounces)", "They are equal", "Neither, walls do not give impulse"],
        answer: 1, trap: "Thinking stopping is the biggest change possible.",
        why: "Sticking: Δp = 0 − mv = −mv. Bouncing: Δp = −mv − mv = −2mv. Reversing direction needs twice the impulse." },
      { q: "A 0.5 kg ball moving at +4 m/s bounces back at −4 m/s from a wall. The contact lasts 0.02 s. What is the average force on the ball?",
        choices: ["100 N", "200 N", "400 N", "0 N"],
        answer: 2, trap: "Forgetting the sign flip makes Δv = 8 m/s, not 0 or 4.",
        why: "Δp = 0.5(−4 − 4) = −4 kg·m/s. F = Δp/Δt = −4 / 0.02 = −200 N. Magnitude 200 N." }
    ]
  },
  {
    id: "energy", title: "Work & Energy", color: "#dc2626",
    questions: [
      { q: "You carry a heavy box horizontally at constant velocity across a room. How much work does your upward lifting force do on the box?",
        choices: ["Weight × distance", "Zero", "Equal to the box's kinetic energy", "Negative"],
        answer: 1, trap: "Effort is not work. W = Fd cos θ.",
        why: "Your force is vertical, the displacement is horizontal, so θ = 90° and cos 90° = 0. No work is done by that force." },
      { q: "A car doubles its speed. What happens to its kinetic energy?",
        choices: ["Doubles", "Triples", "Quadruples", "Stays the same"],
        answer: 2, trap: "Assuming KE is proportional to v.",
        why: "KE = ½mv². Energy goes with v², so 2× speed gives 4× the kinetic energy (and about 4× the braking distance)." },
      { q: "A ball is dropped from 20 m with no air resistance. How fast is it moving just before it hits the ground? (g = 10 m/s²)",
        choices: ["10 m/s", "20 m/s", "40 m/s", "200 m/s"],
        answer: 1, trap: "Forgetting the square root after solving mgh = ½mv².",
        why: "mgh = ½mv² → v = √(2gh) = √(2·10·20) = √400 = 20 m/s. Mass cancels." },
      { q: "A 50 N force pulls a sled 10 m along the ground. The rope makes a 60° angle with the ground. How much work does the force do?",
        choices: ["500 J", "250 J", "433 J", "0 J"],
        answer: 1, trap: "Using the full force instead of its component along the motion.",
        why: "W = Fd cos θ = (50)(10)(cos 60°) = 500 × 0.5 = 250 J." },
      { q: "A motor does 600 J of work in 3 s. What is its power?",
        choices: ["1800 W", "200 W", "600 W", "0.005 W"],
        answer: 1, trap: "Confusing work and power, or inverting the ratio.",
        why: "P = W / t = 600 / 3 = 200 W (200 J every second)." },
      { q: "Two frictionless roller-coaster hills have the same height, but one is a gentle ramp and the other is steep. A cart starts from rest at the top of each. How do the speeds at the bottom compare?",
        choices: ["Steep ramp is faster", "Gentle ramp is faster", "They are equal", "Cannot be determined"],
        answer: 2, trap: "Believing the path shape changes the final speed.",
        why: "Gravitational PE depends only on height. mgh → ½mv² gives the same speed. Only the travel time differs." },
      { q: "A 1000 kg car speeds up from 10 m/s to 20 m/s. How much net work was done on it?",
        choices: ["50,000 J", "100,000 J", "150,000 J", "200,000 J"],
        answer: 2, trap: "Computing ½m(Δv)² instead of ΔKE = ½m(v₂² − v₁²).",
        why: "W_net = ΔKE = ½(1000)(20² − 10²) = 500 × 300 = 150,000 J." },
      { q: "A spring is stretched 2 cm and stores energy E. How much energy does it store when stretched 6 cm?",
        choices: ["3E", "6E", "9E", "36E"],
        answer: 2, trap: "Assuming linear scaling for a quadratic relationship.",
        why: "PE = ½kx². Stretching 3× as far stores 3² = 9 times the energy." }
    ]
  }
];
