// Most-often-missed questions per topic. `answer` is the index of the correct option.
// `trap` names the misconception the wrong answers are built from.
window.TOPICS = [
  {
    id: "kinematics", title: "Kinematics", ngss: "HS-PS2-1 (foundation)",
    questions: [
      { q: "A ball is thrown straight up. At the very top of its path, what are its velocity and acceleration (ignore air)?",
        options: ["v = 0, a = 0", "v = 0, a = 9.8 m/s² downward", "v = 9.8 m/s, a = 0", "v = 0, a = 9.8 m/s² upward"], answer: 1,
        trap: "Zero velocity does not mean zero acceleration.",
        why: "Gravity acts the whole time, so a = g downward even at the peak. Velocity is only momentarily zero while it changes from up to down." },
      { q: "A car speeds up from 0 to 20 m/s in 5 s at constant acceleration. How far does it travel?",
        options: ["20 m", "40 m", "50 m", "100 m"], answer: 2,
        trap: "Using v·t instead of average velocity.",
        why: "a = 4 m/s². d = ½at² = ½(4)(25) = 50 m. Equivalently, average velocity 10 m/s × 5 s. (20 × 5 = 100 would assume the car was at top speed the whole time.)" },
      { q: "On a velocity–time graph, how do you find the displacement?",
        options: ["Read the slope", "Read the y-intercept", "Find the area under the line", "Read the final velocity"], answer: 2,
        trap: "Mixing up slope and area.",
        why: "Slope of v–t = acceleration. Area under v–t = displacement. Slope of x–t = velocity." },
      { q: "You walk 3 m east then 4 m north. What are your distance and the magnitude of displacement?",
        options: ["7 m and 7 m", "7 m and 5 m", "5 m and 7 m", "5 m and 5 m"], answer: 1,
        trap: "Treating displacement as the path length.",
        why: "Distance is the total path (3 + 4 = 7 m). Displacement is the straight line from start to finish: √(3² + 4²) = 5 m." },
      { q: "A runner completes one full lap of a 400 m track in 80 s. What is the average velocity for the lap?",
        options: ["5 m/s", "0 m/s", "400 m/s", "80 m/s"], answer: 1,
        trap: "Confusing average speed with average velocity.",
        why: "Displacement for a full lap is 0, so average velocity is 0. Average speed is 400/80 = 5 m/s." },
      { q: "An object is moving at v = −5 m/s with acceleration a = −2 m/s². What is happening?",
        options: ["It is slowing down", "It is speeding up", "It is moving at constant speed", "It is at rest"], answer: 1,
        trap: "\"Negative acceleration means slowing down.\"",
        why: "Velocity and acceleration point the same way (both negative), so speed increases. Slowing down happens when they have opposite signs." },
      { q: "A rock is dropped from rest. Ignoring air, how far has it fallen after 2.0 s? (g = 9.8 m/s²)",
        options: ["9.8 m", "19.6 m", "39.2 m", "4.9 m"], answer: 1,
        trap: "Forgetting that distance depends on t², or forgetting the ½.",
        why: "d = ½gt² = ½(9.8)(2²) = 19.6 m." },
      { q: "A heavy rock and a light rock are dropped together from the same height (no air resistance). Which hits first?",
        options: ["The heavy rock", "The light rock", "They hit at the same time", "It depends on their shapes only"], answer: 2,
        trap: "\"Heavier objects fall faster.\"",
        why: "Acceleration due to gravity is the same for all masses. The bigger force on the heavy rock is cancelled by its larger inertia." },
      { q: "On a position–time graph, a horizontal line means the object is…",
        options: ["Moving at constant speed", "Accelerating", "At rest", "Moving backward"], answer: 2,
        trap: "Reading the graph as a picture of the path.",
        why: "Slope of x–t is velocity. A horizontal line has zero slope, so zero velocity: the object is staying at one position." }
    ]
  },
  {
    id: "projectile", title: "Projectile Motion", ngss: "HS-PS2-1",
    questions: [
      { q: "One ball is dropped and another is launched horizontally from the same height at the same instant. Which lands first?",
        options: ["The dropped ball", "The launched ball", "They land together", "It depends on the launch speed"], answer: 2,
        trap: "Thinking horizontal speed changes fall time.",
        why: "Vertical motion is independent of horizontal motion. Both start with vy = 0 and fall the same height under g." },
      { q: "At the top of a projectile's path (launched at an angle, no air), which statement is true?",
        options: ["Velocity = 0 and a = 0", "vy = 0, vx ≠ 0, and a = 9.8 m/s² down", "vx = 0 and vy is maximum", "Speed is at its maximum"], answer: 1,
        trap: "Believing the whole velocity vanishes at the peak.",
        why: "Only the vertical component is zero. The horizontal component is unchanged and gravity keeps accelerating the ball downward. Speed is at its minimum at the top." },
      { q: "A projectile is launched from the ground at a speed v. Which pair of launch angles gives the same range?",
        options: ["30° and 45°", "30° and 60°", "20° and 50°", "45° and 90°"], answer: 1,
        trap: "Not knowing range depends on sin 2θ.",
        why: "Range ∝ sin(2θ). Complementary angles (θ and 90° − θ) give the same range; 45° gives the maximum." },
      { q: "A ball is launched at 20 m/s at 30° above horizontal. What is its initial vertical velocity?",
        options: ["17.3 m/s", "10 m/s", "20 m/s", "34.6 m/s"], answer: 1,
        trap: "Swapping sin and cos.",
        why: "vy = v sin θ = 20 sin 30° = 10 m/s. (vx = v cos θ = 17.3 m/s.)" },
      { q: "A ball rolls off a 45 m high cliff horizontally. About how long until it hits the ground? (g = 9.8 m/s²)",
        options: ["1.5 s", "3.0 s", "4.6 s", "9.2 s"], answer: 1,
        trap: "Forgetting to take the square root.",
        why: "45 = ½(9.8)t² → t² = 9.18 → t ≈ 3.0 s." },
      { q: "Ignoring air resistance, what is the horizontal acceleration of a projectile in flight?",
        options: ["9.8 m/s²", "Depends on launch speed", "Zero", "Decreasing"], answer: 2,
        trap: "Thinking something must keep pushing it forward.",
        why: "No horizontal force acts, so ax = 0 and vx is constant. (Newton's first law.)" },
      { q: "If you double the launch speed of a projectile (same angle, same height), the range becomes…",
        options: ["2×", "4×", "√2×", "8×"], answer: 1,
        trap: "Assuming linear scaling.",
        why: "Range = v² sin(2θ)/g, so range scales with v². Doubling v gives 4× the range." },
      { q: "A ball is kicked from level ground and lands on level ground. How does its speed just before landing compare with its launch speed?",
        options: ["Smaller", "Equal", "Larger", "Zero"], answer: 1,
        trap: "Thinking the ball loses speed as it falls.",
        why: "By symmetry (and conservation of energy), the speed at equal heights is equal. Only the direction of vy flips." }
    ]
  },
  {
    id: "newton", title: "Newton's Laws", ngss: "HS-PS2-1, HS-PS2-4",
    questions: [
      { q: "A hockey puck slides at constant velocity on frictionless ice. What is the net force on it?",
        options: ["Forward, in the direction of motion", "Zero", "Equal to its weight", "Decreasing over time"], answer: 1,
        trap: "\"Force is needed to keep something moving.\"",
        why: "Newton's 1st law: constant velocity means zero net force. Force changes motion; it doesn't maintain it." },
      { q: "A truck hits a bug. Compare the force of the truck on the bug to the force of the bug on the truck.",
        options: ["Truck's force is larger", "Bug's force is larger", "They are equal in size and opposite in direction", "They are equal and in the same direction"], answer: 2,
        trap: "Bigger or faster objects exert bigger forces.",
        why: "Newton's 3rd law: equal and opposite, always. The bug's acceleration is huge only because its mass is tiny (a = F/m)." },
      { q: "A 10 kg object is on the Moon (g ≈ 1.6 m/s²). Its mass and weight are about…",
        options: ["10 kg and 98 N", "1.6 kg and 16 N", "10 kg and 16 N", "10 kg and 10 N"], answer: 2,
        trap: "Mixing up mass and weight.",
        why: "Mass is the amount of matter and doesn't change. Weight = mg = 10 × 1.6 ≈ 16 N." },
      { q: "A net force of 30 N acts on a 10 kg cart. What is its acceleration?",
        options: ["0.33 m/s²", "3 m/s²", "300 m/s²", "30 m/s²"], answer: 1,
        trap: "Inverting F = ma.",
        why: "a = F/m = 30/10 = 3 m/s²." },
      { q: "A book rests on a table. Which force is the Newton's-3rd-law partner of the table's normal force on the book?",
        options: ["The book's weight (gravity from Earth)", "The book's pull on the table", "Friction", "The table's weight"], answer: 1,
        trap: "Treating weight and normal force as an action–reaction pair.",
        why: "Third-law pairs act on different objects and are the same type of force. The partner of \"table pushes up on book\" is \"book pushes down on table.\"" },
      { q: "You stand on a scale in an elevator that is accelerating upward. The scale reads…",
        options: ["Less than your weight", "Exactly your weight", "More than your weight", "Zero"], answer: 2,
        trap: "Confusing motion direction with net force.",
        why: "Net force is upward, so N − mg = ma gives N = m(g + a) > mg." },
      { q: "You push a heavy crate but it doesn't move. How does the friction force compare with your push?",
        options: ["Friction is less than your push", "Friction equals your push", "Friction is greater than your push", "There is no friction"], answer: 1,
        trap: "Thinking friction always equals μN.",
        why: "Static friction adjusts up to a maximum μsN. The crate isn't accelerating, so net force = 0 and friction equals the push." },
      { q: "A skydiver reaches terminal velocity. Which statement is correct?",
        options: ["Gravity stops acting", "Air resistance equals her weight and net force is zero", "Air resistance is larger than weight", "She is accelerating at 9.8 m/s²"], answer: 1,
        trap: "Thinking constant speed requires net force.",
        why: "At terminal velocity, drag = weight, so net force = 0 and acceleration = 0." },
      { q: "A 5 kg block slides down a frictionless 30° incline. What is its acceleration? (g = 9.8 m/s²)",
        options: ["9.8 m/s²", "8.5 m/s²", "4.9 m/s²", "2.5 m/s²"], answer: 2,
        trap: "Using g instead of the component along the incline.",
        why: "a = g sin θ = 9.8 × 0.5 = 4.9 m/s². Mass cancels out." }
    ]
  },
  {
    id: "momentum", title: "Momentum", ngss: "HS-PS2-2, HS-PS2-3",
    questions: [
      { q: "What is the momentum of a 1000 kg car traveling at 20 m/s?",
        options: ["50 kg·m/s", "20,000 kg·m/s", "200,000 kg·m/s", "10,000 kg·m/s"], answer: 1,
        trap: "Using ½mv² (kinetic energy) instead of mv.",
        why: "p = mv = 1000 × 20 = 20,000 kg·m/s." },
      { q: "A crash-test car stops in 0.1 s with an airbag instead of 0.01 s without. The airbag mainly reduces…",
        options: ["The change in momentum", "The impulse", "The average force", "The car's mass"], answer: 2,
        trap: "Thinking the airbag changes the momentum change.",
        why: "Impulse = FΔt = Δp, and Δp is fixed by the crash. A longer Δt means a smaller average force." },
      { q: "A 2 kg cart at 3 m/s hits a 1 kg cart at rest and they stick together. Their final speed is…",
        options: ["1 m/s", "2 m/s", "3 m/s", "4.5 m/s"], answer: 1,
        trap: "Averaging the speeds or forgetting the combined mass.",
        why: "2(3) = (2 + 1)v → v = 2 m/s." },
      { q: "In a perfectly inelastic collision, which quantity is conserved?",
        options: ["Kinetic energy only", "Momentum only", "Both momentum and kinetic energy", "Neither"], answer: 1,
        trap: "Believing \"inelastic\" means momentum is lost.",
        why: "Momentum is conserved in every collision with no external net force. Kinetic energy is lost to heat, sound, and deformation." },
      { q: "Two identical carts approach each other at the same speed and stick together. What is their final velocity?",
        options: ["The original speed", "Half the original speed", "Zero", "Twice the original speed"], answer: 2,
        trap: "Forgetting momentum is a vector.",
        why: "Total momentum = mv + m(−v) = 0, so the stuck-together carts end at rest." },
      { q: "A 0.5 kg ball hits a wall at 10 m/s and bounces straight back at 10 m/s. What is the magnitude of its change in momentum?",
        options: ["0", "5 kg·m/s", "10 kg·m/s", "20 kg·m/s"], answer: 2,
        trap: "Thinking same speed means no change in momentum.",
        why: "Δp = m(vf − vi) = 0.5(−10 − 10) = −10, so the magnitude is 10 kg·m/s." },
      { q: "A 50 kg skater at rest throws a 5 kg ball forward at 4 m/s. The skater's recoil velocity is about…",
        options: ["0.4 m/s backward", "0.4 m/s forward", "4 m/s backward", "0"], answer: 0,
        trap: "Ignoring the system's total momentum of zero.",
        why: "0 = 5(4) + 50v → v = −0.4 m/s (backward)." },
      { q: "Why does a catcher move their hand backward while catching a fast ball?",
        options: ["To reduce the ball's momentum", "To increase the stopping time and reduce the force", "To increase the impulse", "To increase the ball's speed"], answer: 1,
        trap: "Thinking the goal is to change the impulse.",
        why: "Δp is fixed. Spreading it over a longer Δt gives a smaller average force (F = Δp/Δt)." }
    ]
  },
  {
    id: "energy", title: "Work & Energy", ngss: "HS-PS3-1, HS-PS3-2, HS-PS3-3",
    questions: [
      { q: "You carry a heavy box at constant speed across a level room. How much work do you do on the box?",
        options: ["Force × distance", "Its weight × height", "Zero", "Depends on how heavy it is"], answer: 2,
        trap: "\"Effort\" is not the same as physics work.",
        why: "Your upward force is perpendicular to the displacement, so W = Fd cos 90° = 0." },
      { q: "A 50 N force is applied at 60° above the horizontal to pull a sled 10 m. How much work is done?",
        options: ["500 J", "433 J", "250 J", "0 J"], answer: 2,
        trap: "Forgetting cos θ, or mixing up sin and cos.",
        why: "W = Fd cos θ = 50 × 10 × cos 60° = 250 J." },
      { q: "If a car doubles its speed, its kinetic energy…",
        options: ["Doubles", "Triples", "Quadruples", "Stays the same"], answer: 2,
        trap: "Assuming KE is linear in v.",
        why: "KE = ½mv², so KE ∝ v². Doubling v gives 4× the KE (and 4× the braking distance)." },
      { q: "A ball is dropped from 5 m. About how fast is it going just before it hits the ground? (g = 9.8 m/s²)",
        options: ["5 m/s", "9.9 m/s", "49 m/s", "98 m/s"], answer: 1,
        trap: "Forgetting the square root.",
        why: "mgh = ½mv² → v = √(2gh) = √(98) ≈ 9.9 m/s." },
      { q: "A machine does 600 J of work in 3 s. What is its power?",
        options: ["200 W", "1800 W", "0.005 W", "600 W"], answer: 0,
        trap: "Multiplying instead of dividing.",
        why: "P = W/t = 600/3 = 200 W." },
      { q: "A sliding box comes to a stop because of friction. Where did its kinetic energy go?",
        options: ["It was destroyed", "It became thermal energy", "It became potential energy", "It was stored in the floor as motion"], answer: 1,
        trap: "\"Energy is used up.\"",
        why: "Energy is conserved. Friction converts mechanical energy to thermal energy (and a little sound)." },
      { q: "A spring (k = 200 N/m) is compressed 0.10 m. How much energy is stored in it?",
        options: ["20 J", "10 J", "1 J", "0.1 J"], answer: 2,
        trap: "Using kx or forgetting to square x.",
        why: "PE = ½kx² = ½(200)(0.10)² = 1 J." },
      { q: "Two roller coaster cars, one 500 kg and one 1000 kg, start from rest at the same height on a frictionless track. At the bottom, which is faster?",
        options: ["The 500 kg car", "The 1000 kg car", "They have the same speed", "Not enough information"], answer: 2,
        trap: "Thinking more mass means more speed.",
        why: "mgh = ½mv² and mass cancels, so v = √(2gh) for both." },
      { q: "A 1000 kg car speeds up from 10 m/s to 20 m/s. How much net work was done on it?",
        options: ["10,000 J", "100,000 J", "150,000 J", "300,000 J"], answer: 2,
        trap: "Subtracting speeds before squaring.",
        why: "W = ΔKE = ½(1000)(20² − 10²) = 500 × 300 = 150,000 J." }
    ]
  }
];
