"""Single source of truth for the Physics learning project.

Run `python3 tools/build.py` to regenerate docs/*.md and site/data.js from this file.
"""

COURSE = {
    "title": "Physics & Earth Science: Semester 1 Learning Project",
    "grade": "11th grade (California NGSS Physics & Earth Science course model)",
    "g": "g = 9.8 m/s² (use 10 m/s² only for quick estimates)",
}

NGSS = {
    "HS-PS2-1": "Analyze data to support the claim that Newton's second law of motion describes the mathematical relationship among the net force on a macroscopic object, its mass, and its acceleration.",
    "HS-PS2-2": "Use mathematical representations to support the claim that the total momentum of a system of objects is conserved when there is no net force on the system.",
    "HS-PS2-3": "Apply scientific and engineering ideas to design, evaluate, and refine a device that minimizes the force on a macroscopic object during a collision.",
    "HS-PS3-1": "Create a computational model to calculate the change in the energy of one component in a system when the change in energy of the other component(s) and energy flows in and out of the system are known.",
    "HS-PS3-2": "Develop and use models to illustrate that energy at the macroscopic scale can be accounted for as a combination of energy associated with the motions of particles (objects) and energy associated with the relative positions of particles (objects).",
    "HS-PS3-3": "Design, build, and refine a device that works within given constraints to convert one form of energy into another form of energy.",
}

UNITS = [
    # ------------------------------------------------------------------ 1
    {
        "id": "kinematics",
        "num": 1,
        "title": "Kinematics",
        "weeks": "3 weeks",
        "standards": ["HS-PS2-1"],
        "standards_note": "Kinematics has no stand-alone NGSS performance expectation. It builds the motion vocabulary and graph/equation skills students need to analyze acceleration data for HS-PS2-1.",
        "essential_question": "How can we describe and predict motion using words, graphs, and equations?",
        "objectives": [
            "Distinguish distance from displacement and speed from velocity, and give the sign (direction) of each.",
            "Calculate average velocity and acceleration from data tables and graphs.",
            "Interpret position-time, velocity-time, and acceleration-time graphs (slope and area).",
            "Select and apply the constant-acceleration equations to solve one-dimensional problems.",
            "Model free fall as constant acceleration of 9.8 m/s² downward, independent of mass (no air resistance).",
        ],
        "concepts": [
            ("Position, distance, displacement", "Position is where an object is relative to an origin. Distance is the total path length (scalar). Displacement is the change in position, Δx = x_f − x_i (vector)."),
            ("Speed vs. velocity", "Speed = distance/time (scalar). Velocity = displacement/time (vector); its sign gives direction."),
            ("Acceleration", "a = Δv/Δt. Any change in velocity (speeding up, slowing down, OR turning) is acceleration. Units: m/s²."),
            ("Graph meaning", "x-t slope = velocity. v-t slope = acceleration; v-t area = displacement. a-t area = change in velocity."),
            ("Constant-acceleration equations", "v = v₀ + at;  Δx = v₀t + ½at²;  v² = v₀² + 2aΔx;  Δx = ½(v + v₀)t."),
            ("Free fall", "Only gravity acts. a = −9.8 m/s² (down) the whole time, including at the top of a toss."),
        ],
        "formulas": ["v̄ = Δx/Δt", "a = Δv/Δt", "v = v₀ + at", "Δx = v₀t + ½at²", "v² = v₀² + 2aΔx"],
        "cornell": [
            ("What is the difference between distance and displacement?", "Distance: total path traveled (scalar, always ≥ 0). Displacement: straight-line change in position with direction (vector). Walk 40 m east then 30 m west → distance 70 m, displacement 10 m east."),
            ("Speed vs. velocity?", "Speed = distance ÷ time (no direction). Velocity = displacement ÷ time (has direction). Moving in a circle at constant speed = changing velocity."),
            ("Define acceleration. Sign rules?", "a = Δv/Δt. If v and a have the SAME sign the object speeds up; OPPOSITE signs → slows down. Sign shows direction, not 'fast' or 'slow'."),
            ("How do I read an x-t graph?", "Slope = velocity. Straight line = constant v. Curve = changing v. Flat = at rest."),
            ("How do I read a v-t graph?", "Slope = acceleration. Area between line and axis = displacement (area below the axis counts negative). Crossing the axis = turning around."),
            ("Which kinematic equation do I use?", "List knowns/unknown (x, v₀, v, a, t). Pick the equation that has the unknown and NO missing variable. 'No time given' → v² = v₀² + 2aΔx."),
            ("What is special about free fall?", "a = 9.8 m/s² downward at every moment (rising, at the top, falling). v = 0 at the top but a is NOT 0. Mass doesn't matter without air resistance."),
        ],
        "summary": "Kinematics describes motion without asking what causes it. Vectors (displacement, velocity, acceleration) carry direction; graphs and four equations connect them. Free fall is the key example of constant acceleration.",
        "misconceptions": [
            "Velocity is zero ⇒ acceleration is zero (false at the top of a toss).",
            "Negative acceleration always means slowing down (depends on velocity's sign).",
            "Heavier objects fall faster (only with air resistance).",
            "Average speed over two legs = average of the two speeds (only if equal TIMES).",
        ],
        "resources": [
            ("PhET: Moving Man simulation", "https://phet.colorado.edu/en/simulations/moving-man"),
            ("The Physics Classroom: 1-D Kinematics", "https://www.physicsclassroom.com/class/1DKin"),
            ("Khan Academy: One-dimensional motion", "https://www.khanacademy.org/science/physics/one-dimensional-motion"),
            ("HyperPhysics: Kinematics", "http://hyperphysics.phy-astr.gsu.edu/hbase/mot.html"),
            ("IXL Physics: Kinematics skills", "https://www.ixl.com/science/physics"),
        ],
        "labs": ["Motion-detector walk-the-graph lab (match x-t and v-t graphs)", "Free-fall timing lab: photogate or phone slow-motion video, find g from data"],
        "practice": [
            ("A runner covers 100 m east in 12.5 s. What is the average velocity?", "8.0 m/s east"),
            ("A car goes from rest to 27 m/s in 9.0 s. Find a and the distance traveled.", "a = 3.0 m/s²; Δx = ½(27)(9) = 121.5 m"),
            ("A ball is dropped from 78.4 m. How long to land and how fast is it going?", "t = √(2·78.4/9.8) = 4.0 s; v = 9.8·4.0 = 39.2 m/s"),
            ("A car at 25 m/s brakes at 5.0 m/s². Stopping distance and time?", "Δx = 25²/(2·5) = 62.5 m; t = 5.0 s"),
            ("A v-t graph rises from 0 to 10 m/s in 5 s, then stays at 10 m/s for 5 s. Total displacement?", "25 m + 50 m = 75 m"),
            ("A ball is thrown straight up at 14.7 m/s. Time to the top and maximum height?", "t = 1.5 s; h = 14.7²/(2·9.8) ≈ 11.0 m"),
        ],
        "real_world": [
            "Traffic safety: stopping distance grows with the SQUARE of speed (v² = 2aΔx), which is why speed limits drop near schools.",
            "Sports analytics: sprint start acceleration and 40-yard dash splits.",
            "Aviation and rocketry: takeoff roll length and launch acceleration profiles.",
            "GPS/phone sensors: accelerometers integrate acceleration into velocity and position.",
        ],
        "quiz": [
            {"q": "A hiker walks 40 m east, then 30 m west. What is her displacement?",
             "c": ["70 m east", "10 m east", "10 m west", "70 m, no direction"], "a": 1,
             "why": "Displacement is net change in position: +40 − 30 = +10 m (east). 70 m is the distance.",
             "miss": "Confusing distance (scalar) with displacement (vector)."},
            {"q": "A ball is tossed straight up. At the very top of its path, its velocity and acceleration are:",
             "c": ["v = 0, a = 0", "v = 0, a = 9.8 m/s² down", "v = 9.8 m/s up, a = 0", "v = 0, a = 9.8 m/s² up"], "a": 1,
             "why": "Gravity acts the entire flight, so a = 9.8 m/s² downward even when v = 0 for an instant.",
             "miss": "Thinking zero velocity means zero acceleration."},
            {"q": "On a velocity-time graph, the slope of the line represents:",
             "c": ["displacement", "velocity", "acceleration", "distance"], "a": 2,
             "why": "slope = Δv/Δt = acceleration. Displacement is the AREA under the line.",
             "miss": "Mixing up what slope and area mean on different graphs."},
            {"q": "A cart has velocity −5 m/s and acceleration −2 m/s². The cart is:",
             "c": ["speeding up", "slowing down", "moving at constant speed", "at rest"], "a": 0,
             "why": "v and a have the same sign (both negative), so speed increases.",
             "miss": "'Negative acceleration' does not automatically mean slowing down."},
            {"q": "Ignoring air resistance, a 10 kg ball and a 1 kg ball are dropped from the same height at the same time. The 10 kg ball:",
             "c": ["lands first", "lands second", "lands at the same time", "can't be determined"], "a": 2,
             "why": "Both have a = g. Mass cancels in free fall.",
             "miss": "Believing heavier objects fall faster."},
            {"q": "A car starts from rest and accelerates at 3 m/s² for 4 s. How far does it travel?",
             "c": ["12 m", "24 m", "48 m", "6 m"], "a": 1,
             "why": "Δx = ½at² = ½(3)(16) = 24 m. (12 m = a·t is the final speed.)",
             "miss": "Forgetting the ½ and the t², or reporting speed instead of distance."},
            {"q": "A car drives at constant speed around a circular track. Its velocity is:",
             "c": ["constant", "changing because the direction changes", "zero", "changing only if speed changes"], "a": 1,
             "why": "Velocity is a vector; changing direction is a change in velocity (acceleration).",
             "miss": "Treating velocity as only a number (speed)."},
            {"q": "A driver travels 120 km at 60 km/h, then 120 km at 40 km/h. What is the average speed for the whole trip?",
             "c": ["50 km/h", "48 km/h", "100 km/h", "40 km/h"], "a": 1,
             "why": "Total distance 240 km; times 2 h + 3 h = 5 h; 240/5 = 48 km/h. Averaging the speeds only works for equal TIMES.",
             "miss": "Averaging the two speeds instead of total distance ÷ total time."},
            {"q": "An object in free fall drops 4.9 m in its first second. How far has it dropped after 2 seconds (from the start)?",
             "c": ["9.8 m", "14.7 m", "19.6 m", "4.9 m"], "a": 2,
             "why": "Δx = ½gt² grows with t². Doubling t quadruples distance: 4 × 4.9 = 19.6 m.",
             "miss": "Assuming distance is proportional to time (linear)."},
            {"q": "Which equation is the best choice for finding stopping distance when you know v₀, v = 0, and a, but NOT t?",
             "c": ["v = v₀ + at", "Δx = v₀t + ½at²", "v² = v₀² + 2aΔx", "a = Δv/Δt"], "a": 2,
             "why": "It contains Δx and no t, so it needs only the known quantities.",
             "miss": "Picking an equation that contains an unknown time."},
        ],
    },
    # ------------------------------------------------------------------ 2
    {
        "id": "projectile-motion",
        "num": 2,
        "title": "Projectile Motion",
        "weeks": "2 weeks",
        "standards": ["HS-PS2-1"],
        "standards_note": "Projectile motion applies Newton's second law in two independent dimensions (constant a_y = −g, a_x = 0) and uses data/graph analysis aligned with HS-PS2-1.",
        "essential_question": "How can we predict where a thrown or launched object will land?",
        "objectives": [
            "Explain why horizontal and vertical motion are independent and what stays constant in each.",
            "Resolve an initial velocity into x and y components using trigonometry.",
            "Calculate time of flight, range, and maximum height for horizontal and angled launches.",
            "Predict how changing launch angle or speed affects range and flight time.",
            "Design and test a launcher experiment and compare data with predictions.",
        ],
        "concepts": [
            ("Independence of motion", "Horizontal and vertical motions happen at the same time but do not affect each other. Time connects them."),
            ("Horizontal motion", "No horizontal force (ignoring air) ⇒ a_x = 0 and v_x is constant: x = v_x·t."),
            ("Vertical motion", "Free fall: a_y = −9.8 m/s². Use the kinematic equations with v_y."),
            ("Components", "v_x = v cosθ;  v_y = v sinθ."),
            ("Angled launch from level ground", "T = 2v_y/g;  R = v²sin2θ/g;  H = v_y²/(2g)."),
            ("Symmetry & range", "Complementary angles (30°/60°) give equal range; 45° gives maximum range (no air resistance, level ground)."),
        ],
        "formulas": ["v_x = v cosθ", "v_y = v sinθ", "x = v_x t", "y = y₀ + v_y t − ½gt²", "R = v² sin2θ / g"],
        "cornell": [
            ("What does 'independent' mean here?", "Horizontal and vertical motion don't influence each other. A dropped ball and a ball shot horizontally from the same height hit the ground together."),
            ("What is happening horizontally?", "Constant velocity (a_x = 0). Use x = v_x·t."),
            ("What is happening vertically?", "Constant acceleration g downward. Use v_y = v_{y0} − gt, y = v_{y0}t − ½gt²."),
            ("How do I break a launch speed into components?", "v_x = v·cosθ, v_y = v·sinθ (θ above horizontal). Draw a right triangle."),
            ("What is true at the peak?", "v_y = 0 but v_x ≠ 0 (still moving sideways). a = 9.8 m/s² down. Speed is minimum at the peak."),
            ("How to solve a horizontal launch?", "1) Use height to get t = √(2h/g). 2) Use t to get range x = v_x·t. 3) v_y at landing = gt."),
            ("Angle and range?", "Max range at 45°. θ and 90°−θ give the same range; higher angle → longer time and higher peak. Range ∝ v²."),
        ],
        "summary": "A projectile is any object moving under gravity alone. Treat x and y separately: constant velocity horizontally, constant downward acceleration vertically, linked by the shared time.",
        "misconceptions": [
            "A force is needed to keep the projectile moving forward (no—inertia).",
            "At the peak, acceleration is zero.",
            "A horizontally launched ball takes longer to fall than a dropped one.",
            "Doubling launch speed doubles range (it quadruples it).",
        ],
        "resources": [
            ("PhET: Projectile Motion simulation", "https://phet.colorado.edu/en/simulations/projectile-motion"),
            ("The Physics Classroom: Projectile Motion", "https://www.physicsclassroom.com/class/vectors"),
            ("Khan Academy: Two-dimensional projectile motion", "https://www.khanacademy.org/science/physics/two-dimensional-motion"),
            ("HyperPhysics: Projectile motion", "http://hyperphysics.phy-astr.gsu.edu/hbase/traj.html"),
        ],
        "labs": ["Marble-launcher lab: predict landing spot of a horizontal launch, then test", "Video analysis (Tracker / phone video) of a basketball shot: plot x-t and y-t"],
        "practice": [
            ("A ball is kicked horizontally at 12 m/s from a 44.1 m cliff. Find flight time, range, and vertical speed on impact.", "t = 3.0 s; x = 36 m; v_y = 29.4 m/s downward"),
            ("A ball launches at 25 m/s at 37° (sin = 0.6, cos = 0.8). Find v_x, v_y, time of flight, range, and max height.", "v_x = 20 m/s; v_y = 15 m/s; T = 3.06 s; R ≈ 61 m; H ≈ 11.5 m"),
            ("A football is kicked at 30 m/s at 45°. Find the range.", "R = 30²·sin90°/9.8 ≈ 91.8 m"),
            ("A plane flying horizontally at 100 m/s drops a package from 490 m. How far ahead of the drop point does it land?", "t = 10 s; x = 1000 m"),
            ("Two balls are launched at the same speed, one at 30° and one at 60°. Compare range and time in the air.", "Same range; the 60° ball stays up longer and goes higher."),
            ("A stone thrown horizontally from a bridge lands 20 m away after 2.0 s. Find its initial speed and the bridge height.", "v = 10 m/s; h = ½(9.8)(4) = 19.6 m"),
        ],
        "real_world": [
            "Sports: basketball free throws, soccer kicks, javelin and long-jump angles (real optimal angles are below 45° because release height and air resistance matter).",
            "Emergency response: water-hose streams and fire-fighting aerial drops.",
            "Engineering: conveyor/ramp design and package drops; video game physics engines.",
            "Space and defense: ballistics and satellite launch trajectories (extension).",
        ],
        "quiz": [
            {"q": "Ignoring air resistance, what is the horizontal acceleration of a projectile in flight?",
             "c": ["9.8 m/s²", "Zero", "It decreases over time", "It equals the launch speed"], "a": 1,
             "why": "No horizontal force acts, so a_x = 0 and v_x is constant.",
             "miss": "Believing a 'force of the throw' keeps acting on the object."},
            {"q": "One ball is dropped and another is shot horizontally from the same height at the same instant. Which lands first?",
             "c": ["the dropped ball", "the horizontally shot ball", "they land together", "depends on the shot speed"], "a": 2,
             "why": "Vertical motion is identical (both start with v_y = 0 and a = g). Horizontal speed doesn't change fall time.",
             "miss": "Thinking horizontal velocity changes vertical motion."},
            {"q": "At the highest point of a projectile's path (launched at an angle), which statement is correct?",
             "c": ["v = 0 and a = 0", "v_y = 0 and a = 9.8 m/s² down", "v_x = 0 and a = 9.8 m/s² down", "the speed is at its maximum"], "a": 1,
             "why": "Only the vertical component is zero at the peak; horizontal velocity continues and gravity still accelerates it.",
             "miss": "Treating the peak as a momentary stop for the whole object."},
            {"q": "A ball is launched at 20 m/s at 30° above horizontal. What is its initial vertical velocity?",
             "c": ["17.3 m/s", "10 m/s", "20 m/s", "34.6 m/s"], "a": 1,
             "why": "v_y = 20 sin30° = 10 m/s. (17.3 m/s is v_x = 20 cos30°.)",
             "miss": "Swapping sine and cosine."},
            {"q": "A ball is launched at 30° and another at 60° with the same speed from level ground. Compared with the 30° ball, the 60° ball has:",
             "c": ["a shorter range", "a longer range", "the same range", "a range of zero"], "a": 2,
             "why": "R = v² sin2θ/g and sin60° = sin120°. Complementary angles give equal range.",
             "miss": "Assuming a bigger angle must mean a longer range."},
            {"q": "Ignoring air resistance and launching from level ground, which angle gives the maximum range?",
             "c": ["30°", "45°", "60°", "90°"], "a": 1,
             "why": "sin2θ is maximized when 2θ = 90°.",
             "miss": "Mixing up the range-optimal angle with the max-height angle (90°)."},
            {"q": "A ball rolls horizontally off a 19.6 m high table at 15 m/s. How far from the base of the table does it land?",
             "c": ["15 m", "30 m", "19.6 m", "60 m"], "a": 1,
             "why": "t = √(2·19.6/9.8) = 2.0 s; x = 15·2.0 = 30 m.",
             "miss": "Skipping the time-of-fall step (using height as the range, or not finding t)."},
            {"q": "You stand in a train moving at constant velocity and toss a ball straight up. The ball lands:",
             "c": ["behind you", "ahead of you", "in your hand", "outside the train"], "a": 2,
             "why": "The ball keeps the train's horizontal velocity (no horizontal force), so it stays above your hand.",
             "miss": "Forgetting inertia: the ball shares the train's horizontal motion."},
            {"q": "A projectile is launched, rises, then falls back to its launch height. How does its speed on the way down at launch height compare to its launch speed?",
             "c": ["smaller", "larger", "equal", "zero"], "a": 2,
             "why": "Symmetry: with no air resistance, speed at equal heights is the same (and direction is mirrored).",
             "miss": "Thinking energy is 'used up' on the way."},
            {"q": "If you double the launch speed at the same angle (level ground, no air resistance), the range becomes:",
             "c": ["2 times as big", "4 times as big", "the same", "√2 times as big"], "a": 1,
             "why": "R ∝ v². Doubling v → 4× range.",
             "miss": "Assuming linear scaling."},
        ],
    },
    # ------------------------------------------------------------------ 3
    {
        "id": "newtons-laws",
        "num": 3,
        "title": "Newton's Laws",
        "weeks": "4 weeks",
        "standards": ["HS-PS2-1"],
        "standards_note": "Core unit for HS-PS2-1 (Newton's second law from data). Third law connects to HS-PS2-2 and HS-PS2-3.",
        "essential_question": "How do forces change the motion of objects?",
        "objectives": [
            "State Newton's three laws and identify real examples of each.",
            "Draw free-body diagrams showing all forces on one object.",
            "Use ΣF = ma to find acceleration, force, or mass, including friction, tension, and normal force.",
            "Identify Newton's third-law force pairs (different objects, equal and opposite).",
            "Analyze lab data (force vs. acceleration, mass vs. acceleration) to support ΣF = ma.",
        ],
        "concepts": [
            ("Force and net force", "A force is a push or pull (vector, newtons). Net force ΣF is the vector sum of all forces on an object."),
            ("First law (inertia)", "An object keeps its velocity (including rest) unless a net external force acts on it. Mass measures inertia."),
            ("Second law", "a = ΣF/m: acceleration is proportional to net force and inversely proportional to mass, in the direction of net force."),
            ("Third law", "If A pushes on B, B pushes on A with an equal-magnitude, opposite force. The forces act on DIFFERENT objects and never cancel."),
            ("Common forces", "Weight W = mg (down); normal N (perpendicular to the surface); friction f ≤ μN (opposes sliding); tension T (along ropes)."),
            ("Mass vs. weight", "Mass (kg) is the amount of matter and doesn't change. Weight (N) is the gravitational force and depends on location."),
            ("Free-body diagram (FBD)", "Dot for the object; arrows for every force acting ON it; none for forces it exerts on others."),
        ],
        "formulas": ["ΣF = ma", "W = mg", "f_k = μ_k N", "a = ΣF / m"],
        "cornell": [
            ("What is Newton's 1st law?", "Inertia: constant velocity (or rest) unless net force ≠ 0. 'No motion change' ≠ 'no forces' — just balanced forces."),
            ("What is Newton's 2nd law?", "ΣF = ma. Double the force → double a. Double the mass → half a. 1 N = 1 kg·m/s²."),
            ("What is Newton's 3rd law?", "Force pairs are equal, opposite, same type, and on DIFFERENT objects. Truck–car collision: forces on each are equal in size."),
            ("How do I make a free-body diagram?", "1) Isolate object. 2) Draw weight down. 3) Add contact forces (normal, friction, tension, applied). 4) Pick axes. 5) Write ΣF in each direction."),
            ("Mass vs. weight?", "Mass: kg, constant. Weight: mg in N; on the Moon g ≈ 1.6 m/s² so weight is ~1/6."),
            ("What is friction?", "Opposes relative motion/attempted motion. Static f_s ≤ μ_s N (matches applied force until it slips). Kinetic f_k = μ_k N (constant)."),
            ("Apparent weight in an elevator?", "N = m(g + a) when accelerating upward (feel heavier), N = m(g − a) when accelerating downward. At constant velocity N = mg."),
            ("Terminal velocity?", "Drag grows with speed until drag = weight; net force = 0 so a = 0 and speed is constant (not zero!)."),
        ],
        "summary": "Forces cause changes in velocity (acceleration), not velocity itself. Always draw a free-body diagram, add forces as vectors to find ΣF, then apply ΣF = ma. Third-law pairs act on different objects.",
        "misconceptions": [
            "Motion requires a continuing force.",
            "Normal force and weight are a third-law pair (they act on the same object).",
            "Bigger objects exert bigger forces in a collision.",
            "Mass and weight are the same thing.",
        ],
        "resources": [
            ("PhET: Forces and Motion: Basics", "https://phet.colorado.edu/en/simulations/forces-and-motion-basics"),
            ("The Physics Classroom: Newton's Laws", "https://www.physicsclassroom.com/class/newtlaws"),
            ("Khan Academy: Forces and Newton's laws of motion", "https://www.khanacademy.org/science/physics/forces-newtons-laws"),
            ("HyperPhysics: Newton's Laws", "http://hyperphysics.phy-astr.gsu.edu/hbase/newt.html"),
        ],
        "labs": ["Cart-and-hanging-mass lab: graph a vs. F (constant mass) and a vs. 1/m (constant force)", "Friction-coefficient lab: pull a block with a force sensor, compare static vs. kinetic", "Egg-drop / seatbelt crash cart (links to HS-PS2-3)"],
        "practice": [
            ("A 1200 kg car experiences a net force of 3000 N. Find its acceleration.", "a = 2.5 m/s²"),
            ("A 5.0 kg box is pulled with 30 N while friction is 10 N. Find a.", "ΣF = 20 N → a = 4.0 m/s²"),
            ("What is the weight of a 70 kg student on Earth and on the Moon (g = 1.62 m/s²)?", "686 N on Earth; ≈ 113 N on the Moon. Mass stays 70 kg."),
            ("A 60 kg person stands on a scale in an elevator accelerating upward at 2.0 m/s². What does the scale read?", "N = 60(9.8 + 2.0) = 708 N"),
            ("A frictionless 30° incline: what is a block's acceleration?", "a = g sin30° = 4.9 m/s² down the slope"),
            ("A 2 kg block touches a 3 kg block on frictionless ice. A 10 N push is applied to the 2 kg block. Find a and the contact force on the 3 kg block.", "a = 2 m/s²; force on 3 kg block = 6 N"),
        ],
        "real_world": [
            "Automotive safety: seat belts (inertia), crumple zones and ABS (friction control).",
            "Aerospace: rocket thrust and reaction forces; astronaut weightlessness vs. mass.",
            "Sports: starting blocks (third law), skiing and sled friction, parachute terminal velocity.",
            "Amusement-park rides: apparent weight in roller coasters and drop towers.",
        ],
        "quiz": [
            {"q": "A hockey puck slides at constant velocity across frictionless ice. The net force on the puck is:",
             "c": ["in the direction of motion", "zero", "equal to its weight", "decreasing over time"], "a": 1,
             "why": "Constant velocity means a = 0, so ΣF = 0. No force is needed to maintain motion.",
             "miss": "Believing motion requires a continuing push (Aristotelian idea)."},
            {"q": "A book rests on a table. Which force is the Newton's third-law partner of the book's weight (Earth's pull on the book)?",
             "c": ["the table's normal force on the book", "the book's pull on Earth", "the book's push on the table", "friction"], "a": 1,
             "why": "Third-law pairs: Earth pulls book ↔ book pulls Earth. Weight and normal force act on the same object, so they are not a pair.",
             "miss": "Treating the normal force as the 'reaction' to weight."},
            {"q": "A large truck collides head-on with a small car. During the collision, the force on the car is ___ the force on the truck.",
             "c": ["greater than", "less than", "equal in magnitude to", "zero compared with"], "a": 2,
             "why": "Third law: forces are equal and opposite. The car's larger acceleration comes from its smaller mass.",
             "miss": "Thinking the bigger object exerts a bigger force."},
            {"q": "A 10 N net force acts on a 2 kg cart. What is its acceleration?",
             "c": ["0.2 m/s²", "5 m/s²", "20 m/s²", "12 m/s²"], "a": 1,
             "why": "a = F/m = 10/2 = 5 m/s².",
             "miss": "Multiplying instead of dividing (or inverting the ratio)."},
            {"q": "An astronaut has a mass of 80 kg on Earth. On the Moon, her mass is:",
             "c": ["about 13 kg", "80 kg", "about 130 kg", "zero"], "a": 1,
             "why": "Mass doesn't change with location; weight does.",
             "miss": "Confusing mass with weight."},
            {"q": "You stand on a scale in an elevator that is accelerating UPWARD. The scale reading is:",
             "c": ["less than mg", "equal to mg", "greater than mg", "zero"], "a": 2,
             "why": "N − mg = ma (a up) → N = m(g + a) > mg.",
             "miss": "Assuming the reading always equals weight."},
            {"q": "A 20 kg crate is pushed across a floor at constant speed with a 50 N horizontal force. The friction force on the crate is:",
             "c": ["0 N", "50 N", "196 N", "less than 50 N"], "a": 1,
             "why": "Constant speed → ΣF = 0, so friction balances the 50 N push.",
             "miss": "Computing friction from weight when the problem gives balanced-force information."},
            {"q": "The same net force is applied to two carts. Cart B has twice the mass of cart A. Cart B's acceleration is:",
             "c": ["twice cart A's", "half of cart A's", "the same as cart A's", "four times cart A's"], "a": 1,
             "why": "a = F/m → doubling m halves a.",
             "miss": "Mixing up direct and inverse proportionality."},
            {"q": "A skydiver reaches terminal velocity. At that moment:",
             "c": ["the net force is downward", "the net force is zero", "the skydiver stops falling", "air resistance is zero"], "a": 1,
             "why": "Drag equals weight, so ΣF = 0 and velocity is constant (but not zero).",
             "miss": "Thinking terminal velocity means no motion or no forces."},
            {"q": "Which free-body diagram for a box sliding down a rough incline is correct?",
             "c": ["weight, normal, and a 'force of motion' down the slope", "weight, normal, and friction up the slope", "weight and normal only", "weight, normal, friction up the slope, and a 'force of the push' down the slope"], "a": 1,
             "why": "Include only real forces from other objects: gravity, normal, friction. There is no 'force of motion'.",
             "miss": "Adding a phantom 'force of motion' to an FBD."},
        ],
    },
    # ------------------------------------------------------------------ 4
    {
        "id": "momentum",
        "num": 4,
        "title": "Momentum",
        "weeks": "3 weeks",
        "standards": ["HS-PS2-2", "HS-PS2-3"],
        "standards_note": "Direct match: conservation of momentum (HS-PS2-2) and engineering a collision-safety device (HS-PS2-3).",
        "essential_question": "How can we predict the outcome of a collision, and how do we make collisions safer?",
        "objectives": [
            "Calculate momentum and recognize that it is a vector.",
            "Relate impulse to change in momentum (J = FΔt = Δp) and interpret F-t graphs.",
            "Apply conservation of momentum to elastic, inelastic, and explosion/recoil problems.",
            "Classify collisions and explain what is and isn't conserved.",
            "Design, test, and refine a device that reduces force during a collision (HS-PS2-3).",
        ],
        "concepts": [
            ("Momentum", "p = mv (kg·m/s), a vector in the direction of velocity."),
            ("Impulse", "J = FΔt = Δp = mv_f − mv_i. Area under a force–time graph equals impulse."),
            ("Impulse–momentum & safety", "For the same Δp, longer contact time ⇒ smaller average force (airbags, crumple zones, padding)."),
            ("Conservation of momentum", "If net external force on a system is zero, total p before = total p after."),
            ("Collision types", "Elastic: p and KE conserved. Inelastic: p conserved, KE lost. Perfectly inelastic: objects stick together (max KE loss)."),
            ("Explosions & recoil", "Starting from rest, total p = 0, so pieces move in opposite directions with equal-size momenta."),
        ],
        "formulas": ["p = mv", "J = FΔt = Δp", "m₁v₁ + m₂v₂ = m₁v₁′ + m₂v₂′", "stuck together: v′ = (m₁v₁ + m₂v₂)/(m₁ + m₂)"],
        "cornell": [
            ("What is momentum?", "p = mv. Vector. A slow truck and a fast bullet can have similar momentum. Units kg·m/s."),
            ("What is impulse?", "J = FΔt = Δp. A force acting over time changes momentum. Units N·s = kg·m/s."),
            ("Why do airbags work?", "Same Δp, but longer Δt → smaller F (F = Δp/Δt). Applies to padding, helmets, crumple zones, bending knees when landing."),
            ("When is momentum conserved?", "In an isolated system (net external force = 0), for ANY collision — elastic or inelastic."),
            ("Elastic vs. inelastic?", "Elastic: KE conserved (billiard balls, approximately). Inelastic: KE converted to heat/sound/deformation. Perfectly inelastic: stick together."),
            ("How do I solve a collision?", "1) Choose + direction. 2) Write p_before = p_after with signs. 3) Solve for the unknown velocity. 4) Check KE if asked."),
            ("Recoil?", "Start at rest: 0 = m₁v₁ + m₂v₂ → v₂ = −(m₁/m₂)v₁. The lighter object moves faster."),
            ("Bounce vs. stick?", "A rebounding object has a bigger Δp (reverses direction) than one that stops, so it receives a bigger impulse."),
        ],
        "summary": "Momentum measures 'how hard it is to stop' a moving object. Forces change momentum over time (impulse). In an isolated system total momentum stays constant, which lets us predict collisions and recoil without knowing the forces.",
        "misconceptions": [
            "Momentum and kinetic energy are the same / both are always conserved.",
            "Momentum is a scalar (direction and signs matter).",
            "Bigger force always means bigger change in momentum (time matters).",
            "In a collision, the heavier object feels more force (third law).",
        ],
        "resources": [
            ("PhET: Collision Lab", "https://phet.colorado.edu/en/simulations/collision-lab"),
            ("The Physics Classroom: Momentum and Its Conservation", "https://www.physicsclassroom.com/class/momentum"),
            ("Khan Academy: Impulse and momentum", "https://www.khanacademy.org/science/physics/linear-momentum"),
            ("HyperPhysics: Momentum", "http://hyperphysics.phy-astr.gsu.edu/hbase/mom.html"),
            ("IIHS (Insurance Institute for Highway Safety): crash test videos", "https://www.iihs.org"),
        ],
        "labs": ["Dynamics-cart collision lab with motion sensors (elastic and sticky)", "Egg-drop / crash-barrier engineering challenge: minimize peak force (HS-PS2-3)", "Impulse lab: force-sensor F-t graph from a bouncing ball"],
        "practice": [
            ("A 0.145 kg baseball moves at 40 m/s. What is its momentum?", "5.8 kg·m/s"),
            ("A 50 N force acts on a 2.0 kg object for 0.20 s. Find the impulse and velocity change.", "J = 10 N·s; Δv = 5.0 m/s"),
            ("A 2 kg cart at 3 m/s hits and sticks to a 1 kg cart at rest. Find the final velocity.", "v′ = 6/3 = 2.0 m/s"),
            ("Two skaters at rest push apart: 60 kg and 40 kg. The 40 kg skater moves at 3 m/s. How fast does the other move?", "2.0 m/s in the opposite direction"),
            ("A 0.060 kg egg moving 5.0 m/s stops in 0.010 s (hard floor) vs 0.10 s (padding). Compare the average forces.", "30 N vs 3 N: 10× less force with padding"),
            ("A 1500 kg car moving 20 m/s east hits a 1000 kg car at rest; they stick. Find the final velocity and KE lost.", "v′ = 12 m/s; KE lost = 300 kJ − 180 kJ = 120 kJ"),
        ],
        "real_world": [
            "Vehicle safety: airbags, crumple zones, seat belts, guardrail crash cushions.",
            "Sports: follow-through in baseball/golf, catching a ball by 'giving' with your hands, helmets.",
            "Rocket propulsion: exhaust momentum balances rocket momentum.",
            "Forensics: crash reconstruction from skid marks and conservation of momentum.",
        ],
        "quiz": [
            {"q": "A 2 kg cart moves at 3 m/s. What is its momentum?",
             "c": ["1.5 kg·m/s", "5 kg·m/s", "6 kg·m/s", "18 kg·m/s"], "a": 2,
             "why": "p = mv = 2 × 3 = 6 kg·m/s.",
             "miss": "Using ½mv² (kinetic energy-like) or v/m."},
            {"q": "Two identical carts move toward each other at equal speeds on a frictionless track. The total momentum of the system is:",
             "c": ["twice one cart's momentum", "zero", "equal to one cart's momentum", "cannot be determined"], "a": 1,
             "why": "Momentum is a vector. +p and −p add to zero.",
             "miss": "Adding magnitudes and ignoring direction."},
            {"q": "Why does an airbag reduce injury in a crash?",
             "c": ["It reduces the passenger's change in momentum", "It increases the stopping time, reducing the average force", "It reduces the passenger's mass", "It increases the impulse"], "a": 1,
             "why": "Δp is fixed by the crash; F = Δp/Δt, so a larger Δt gives a smaller force.",
             "miss": "Believing airbags change the momentum change or 'absorb' force without time."},
            {"q": "A 1000 kg car moving at 10 m/s collides with and sticks to a stationary 1000 kg car. What is their velocity after the collision?",
             "c": ["10 m/s", "5 m/s", "2.5 m/s", "20 m/s"], "a": 1,
             "why": "10 000 = 2000·v′ → v′ = 5 m/s.",
             "miss": "Forgetting that the combined mass is in the denominator."},
            {"q": "In an inelastic collision (no external forces), which quantity is conserved?",
             "c": ["only kinetic energy", "only momentum", "both momentum and kinetic energy", "neither"], "a": 1,
             "why": "Momentum is conserved in all isolated collisions; KE is not conserved in inelastic ones.",
             "miss": "Thinking 'conserved' applies to energy only, or to both in every collision."},
            {"q": "Two identical balls hit a wall with the same speed. Ball A sticks; ball B bounces back at the same speed. Which gets the larger impulse from the wall?",
             "c": ["ball A", "ball B", "equal impulse", "neither receives impulse"], "a": 1,
             "why": "B's momentum changes from +mv to −mv (Δp = 2mv); A's changes by mv.",
             "miss": "Overlooking the sign change in the rebounding case."},
            {"q": "A 4.0 kg rifle fires a 0.010 kg bullet at 400 m/s. Ignoring other forces, the rifle's recoil speed is:",
             "c": ["0.1 m/s", "1.0 m/s", "10 m/s", "400 m/s"], "a": 1,
             "why": "0 = (0.010)(400) + 4.0·v → |v| = 1.0 m/s.",
             "miss": "Forgetting that the recoil velocity is much smaller because of the larger mass."},
            {"q": "The area under a force-versus-time graph equals:",
             "c": ["the change in kinetic energy", "the impulse (change in momentum)", "the acceleration", "the work done"], "a": 1,
             "why": "Area = ∫F dt = J = Δp.",
             "miss": "Confusing F-t area with F-x area (work)."},
            {"q": "A truck and a small car collide head-on. Compared with the truck, the change in momentum of the car has:",
             "c": ["greater magnitude", "smaller magnitude", "equal magnitude", "no relationship"], "a": 2,
             "why": "Forces are equal and opposite for the same time, so impulses and Δp are equal in size. Car's Δv is larger since its mass is smaller.",
             "miss": "Confusing equal Δp with equal Δv."},
            {"q": "Two objects with the same momentum are stopped by equal-size constant forces. Compare the stopping times.",
             "c": ["the heavier takes longer", "the lighter takes longer", "the times are equal", "not enough information"], "a": 2,
             "why": "Δt = Δp/F, and both Δp and F are the same.",
             "miss": "Thinking mass or speed alone determines stopping time."},
        ],
    },
    # ------------------------------------------------------------------ 5
    {
        "id": "work-energy",
        "num": 5,
        "title": "Work & Energy",
        "weeks": "4 weeks",
        "standards": ["HS-PS3-1", "HS-PS3-2", "HS-PS3-3"],
        "standards_note": "Matches HS-PS3-1 (computational energy model), HS-PS3-2 (kinetic and potential energy models), and HS-PS3-3 (device converting energy). HS-PS3-4 (thermal energy) is a stretch connection through friction.",
        "essential_question": "How is energy transferred and transformed, and why is the total always conserved?",
        "objectives": [
            "Calculate work done by a constant force, including the angle between force and displacement.",
            "Calculate kinetic, gravitational potential, and elastic potential energy.",
            "Apply the work–energy theorem and conservation of mechanical energy.",
            "Account for energy lost to friction as thermal energy; compute power and efficiency.",
            "Create a computational model/spreadsheet of energy flows (HS-PS3-1) and design an energy-conversion device (HS-PS3-3).",
        ],
        "concepts": [
            ("Work", "W = Fd cosθ (joules). Only the component of force along the displacement does work. Perpendicular forces do zero work."),
            ("Kinetic energy", "KE = ½mv². Depends on the square of speed."),
            ("Gravitational potential energy", "PE_g = mgh (relative to a chosen zero level)."),
            ("Elastic potential energy", "PE_s = ½kx²."),
            ("Work–energy theorem", "W_net = ΔKE."),
            ("Conservation of energy", "Energy is never created or destroyed: KE + PE + thermal… = constant in an isolated system. Without friction, mechanical energy (KE + PE) is conserved."),
            ("Power & efficiency", "P = W/t (watts). Efficiency = useful energy out ÷ total energy in."),
        ],
        "formulas": ["W = Fd cosθ", "KE = ½mv²", "PE_g = mgh", "PE_s = ½kx²", "W_net = ΔKE", "P = W/t", "E_i + W_ext = E_f + Q"],
        "cornell": [
            ("What is work in physics?", "W = Fd cosθ. Force must cause displacement. Holding a box still or carrying it level at constant speed: zero work by the lifting force (θ = 90°)."),
            ("What is kinetic energy?", "KE = ½mv². Double speed → 4× KE; double mass → 2× KE."),
            ("What is gravitational PE?", "PE = mgh. Depends on height above a reference only, not the path taken."),
            ("What is the work–energy theorem?", "Net work = change in KE. Positive net work speeds up; negative net work slows down."),
            ("How do I use conservation of energy?", "Draw before/after bar charts (LOL diagrams). KE₁ + PE₁ = KE₂ + PE₂ (+ losses). From height h: v = √(2gh)."),
            ("Where does energy go with friction?", "Into thermal energy of surfaces and surroundings. Total energy is still conserved; mechanical energy is not."),
            ("What is power?", "Rate of doing work: P = W/t = Fv. Watt = J/s. A kilowatt-hour is a unit of ENERGY (3.6 MJ)."),
            ("Efficiency?", "Useful out ÷ total in. No device is 100% efficient because some energy always spreads as heat."),
        ],
        "summary": "Work transfers energy. Energy changes form (kinetic, potential, thermal…) but the total remains constant. Energy accounting with bar charts lets us solve speed and height problems without tracking forces in detail.",
        "misconceptions": [
            "Any force applied over time does work (displacement and direction matter).",
            "Energy is 'used up' (it is transformed).",
            "KE is proportional to speed (it is proportional to speed squared).",
            "Power and energy are the same (power is a rate).",
        ],
        "resources": [
            ("PhET: Energy Skate Park", "https://phet.colorado.edu/en/simulations/energy-skate-park"),
            ("The Physics Classroom: Work, Energy, and Power", "https://www.physicsclassroom.com/class/energy"),
            ("Khan Academy: Work and energy", "https://www.khanacademy.org/science/physics/work-and-energy"),
            ("HyperPhysics: Energy", "http://hyperphysics.phy-astr.gsu.edu/hbase/ephe.html"),
            ("U.S. Energy Information Administration: Energy Kids", "https://www.eia.gov/kids/"),
        ],
        "labs": ["Energy Skate Park + spreadsheet model of energy flows (HS-PS3-1)", "Ramp/cart lab: compare PE lost with KE gained, account for friction", "Design challenge: build a device converting stored energy (spring, mousetrap, solar) into motion (HS-PS3-3)"],
        "practice": [
            ("A 40 N force pushes a crate 3.0 m in the direction of the force. How much work is done?", "W = 120 J"),
            ("A 10 N force pulls a wagon 5.0 m at 60° above the horizontal. How much work is done?", "W = 10·5·cos60° = 25 J"),
            ("A 1000 kg car moves at 20 m/s. What is its kinetic energy?", "KE = 200 000 J"),
            ("A 0.50 kg ball is dropped from 10 m. Find its speed and KE at the ground (no air resistance).", "v = 14 m/s; KE = 49 J"),
            ("A motor lifts a 200 kg load 5.0 m in 10 s. Find the work and power.", "W = 9800 J; P = 980 W"),
            ("A 50 kg skater starts at rest at height 4.0 m. At the bottom her speed is 7.0 m/s. How much energy was lost to friction?", "PE = 1960 J; KE = 1225 J; lost = 735 J"),
        ],
        "real_world": [
            "Renewable energy: hydroelectric dams (PE → KE → electrical), wind turbines, and solar efficiency.",
            "Transportation: regenerative braking in hybrids/EVs recovers KE; fuel efficiency and drag.",
            "Roller coasters and skate parks: energy bar charts and top-hill height design.",
            "Household energy: reading the electric bill in kWh and comparing appliance power ratings.",
        ],
        "quiz": [
            {"q": "You carry a heavy box horizontally across a room at constant speed. The work done by your upward lifting force on the box is:",
             "c": ["positive", "negative", "zero", "equal to mgd"], "a": 2,
             "why": "The lifting force is perpendicular to the displacement (cos90° = 0), so it does no work.",
             "miss": "Thinking effort or holding a weight equals physics work."},
            {"q": "A car doubles its speed. Its kinetic energy becomes:",
             "c": ["2 times larger", "4 times larger", "8 times larger", "the same"], "a": 1,
             "why": "KE = ½mv² ∝ v².",
             "miss": "Assuming KE is proportional to speed."},
            {"q": "How much gravitational potential energy does a 2.0 kg book gain when lifted 3.0 m?",
             "c": ["6 J", "19.6 J", "58.8 J", "117.6 J"], "a": 2,
             "why": "mgh = 2.0 × 9.8 × 3.0 = 58.8 J.",
             "miss": "Dropping g from the calculation (or ½ from KE)."},
            {"q": "A frictionless roller-coaster car starts from rest at 20 m high. Its speed at the bottom is about:",
             "c": ["9.8 m/s", "14 m/s", "19.8 m/s", "39.2 m/s"], "a": 2,
             "why": "v = √(2gh) = √(2·9.8·20) ≈ 19.8 m/s, independent of the track's shape.",
             "miss": "Believing a steeper or shorter path changes the final speed; or forgetting the square root."},
            {"q": "A machine does 600 J of work in 3.0 s. Its power output is:",
             "c": ["1800 W", "200 W", "600 W", "0.005 W"], "a": 1,
             "why": "P = W/t = 600/3 = 200 W.",
             "miss": "Multiplying instead of dividing."},
            {"q": "A 2 kg object starts at rest. 50 J of net work is done on it. Its kinetic energy is now:",
             "c": ["25 J", "50 J", "100 J", "0 J"], "a": 1,
             "why": "W_net = ΔKE = KE_f − 0 = 50 J.",
             "miss": "Re-applying ½ or using mass when the theorem already gives KE directly."},
            {"q": "A spring is stretched twice as far as before. The elastic potential energy stored is:",
             "c": ["twice as much", "four times as much", "half as much", "the same"], "a": 1,
             "why": "PE_s = ½kx² ∝ x².",
             "miss": "Assuming linear scaling for spring energy."},
            {"q": "A sliding box slows to a stop on a rough floor. Where did its kinetic energy go?",
             "c": ["It disappeared", "It became thermal energy of the box and floor", "It became potential energy", "It was stored as momentum"], "a": 1,
             "why": "Friction converts mechanical energy into thermal energy; total energy is conserved.",
             "miss": "Believing energy can be lost or destroyed."},
            {"q": "A kilowatt-hour (kWh) is a unit of:",
             "c": ["power", "force", "energy", "current"], "a": 2,
             "why": "kW (power) × h (time) = energy. 1 kWh = 3.6 × 10⁶ J.",
             "miss": "Reading 'kilowatt' as the whole unit and missing the time factor."},
            {"q": "A 10 N force acts at 60° above the horizontal on a wagon that moves 5.0 m horizontally. The work done by the force is:",
             "c": ["50 J", "43 J", "25 J", "0 J"], "a": 2,
             "why": "W = Fd cosθ = 10 × 5 × cos60° = 25 J.",
             "miss": "Ignoring the angle (50 J) or using sin instead of cos (43 J)."},
        ],
    },
]

ASSESSMENT = {
    "scale": [
        (4, "Advanced", "Applies concepts to new situations, explains reasoning with multiple representations, identifies and corrects errors."),
        (3, "Proficient", "Meets the learning goal: correct concepts, setup, and calculations with units; minor slips only."),
        (2, "Developing", "Partial understanding: correct concepts but setup or calculation errors; needs support with graphs or vectors."),
        (1, "Beginning", "Major misconceptions; only completes problems with step-by-step guidance."),
    ],
    "criteria": [
        ("Conceptual understanding", "Explains the physics in words, identifies the correct principle, avoids common misconceptions."),
        ("Problem solving", "Lists knowns/unknown, draws a diagram, selects an equation, solves algebraically, includes units and checks reasonableness."),
        ("Representations", "Moves between words, diagrams (FBDs, energy bars), graphs, and equations."),
        ("Investigation & data (SEP)", "Collects data, graphs it, interprets slope/area, evaluates error, and uses evidence to support a claim."),
        ("Communication (CER)", "Writes a Claim–Evidence–Reasoning response using correct vocabulary."),
    ],
    "mastery": [
        "Unit quiz: 80% or higher (retakes allowed; quiz bank is randomized).",
        "Cornell notes completed with cues, notes, and a 3–4 sentence summary.",
        "At least one lab report scored 3 or higher on the 4-point rubric.",
        "Practice problem set: 5 of 6 correct with work shown.",
        "Performance task for the standard (see below) scored 3 or higher.",
    ],
    "weights": [("Unit quizzes and practice", 25), ("Labs and investigations", 25), ("Performance tasks / projects", 20), ("Cornell notes and homework", 10), ("Unit tests", 20)],
    "tasks": {
        "kinematics": "Prediction lab: use a v-t graph from a motion detector to predict stopping distance, then verify.",
        "projectile-motion": "Launch challenge: hit a target landing spot using only measured v₀ and calculations.",
        "newtons-laws": "HS-PS2-1 lab report: analyze a vs. F and a vs. m data, write a CER supporting ΣF = ma.",
        "momentum": "HS-PS2-3 engineering design: build and refine a device to protect an egg or sensor in a collision, with F-t evidence.",
        "work-energy": "HS-PS3-1/3 model and device: spreadsheet energy model plus a device converting energy, with efficiency analysis.",
    },
}
